### PR TITLE
file renames and path changes

### PR DESCRIPTION
**Pull request by vaibhav-wolfvk**
renames the html files and took them out of the folders.
modified all the links in index, appointment, services html files.

### CODE REVIEW

**Comment by vedant-jain03** [comment]
@vaibhav-wolfvk Kindly share a clip of the solution as well.

**Comment by vaibhav-wolfvk** [comment]
> @vaibhav-wolfvk Kindly share a clip of the solution as well.

@vedant-jain03 

https://user-images.githubusercontent.com/84243486/150168800-90877dee-979f-4919-ac01-9f9e81917df1.mp4


https://user-images.githubusercontent.com/84243486/150170054-88a55ab6-1403-4788-a5dd-9a9697b129e4.mp4

**Comment by vedant-jain03** [comment]
@vaibhav-wolfvk resolve conflicts
You need to update the local repo and then commit

**Comment by vaibhav-wolfvk** [comment]
> @vaibhav-wolfvk resolve conflicts You need to update the local repo and then commit

@vedant-jain03 conflicts resolved

**Pull request merged**
