### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ashutoshkosti1919**

### CODE REVIEW

**Comment by ashutoshkosti1919** [comment]
Make FAQ page.

**Comment by ashutoshkosti1919** [comment]
Made FAQ Page

**Comment by vedant-jain03** [comment]
Kindly share ss for the same or short clip of the output.

**Comment by ashutoshkosti1919** [comment]
Screenshot (123)
Screenshot (124)
Screenshot (125)
Screenshot (126)

**Comment by vedant-jain03** [comment]
Add the link for FAQ's section on the footer for every page.

**Comment by ashutoshkosti1919** [comment]
task done

**Pull request merged**
