### PR TITLE
added privacy policy page

### PR DESCRIPTION
**Pull request by vaibhav-wolfvk**

### CODE REVIEW

**Comment by vedant-jain03** [comment]
Kindly share clip for this or screenshot

**Comment by vaibhav-wolfvk** [comment]
image
image

https://user-images.githubusercontent.com/84243486/151599842-0f983769-5929-4abc-8ed3-ca8f98c0242c.mp4

@vedant-jain03

**Review by vedant-jain03 — CHANGES_REQUESTED** [review]
`
html {
  scroll-behavior: smooth;
}
`
add this in CSS

**Comment by vaibhav-wolfvk** [comment]
@vedant-jain03 requested changes done

**Comment by vedant-jain03** [comment]
@vaibhav-wolfvk Why you changes index.html?
Your changes are crashing the site.
Just add a new page for privacy policy and add the link in the footer.
For ref. checkout how FAQs is being placed

**Comment by vaibhav-wolfvk** [comment]
@vedant sorry I think it happened by mistake, during the merging.
Index page in my local repo  had some changes which crashed it,so in return
I made some changes their to fix it,but it seems it conflicted in the
remote one.

**Comment by vaibhav-wolfvk** [comment]
@vedant will create a new pull request just adding privacy policy page and
changing the links

**Pull request merged**
