### PR TITLE
Ashutosh

### PR DESCRIPTION
**Pull request by ashutoshkosti1919**
changed logo of donor center location and modified links of footer in about page

### CODE REVIEW

**Comment by vedant-jain03** [comment]
Resolve the conflict, update the local repo.
Kindly, Change other footer Page links as well.

**Comment by ashutoshkosti1919** [comment]
I have changed all the page links . Please provide information that which links I have to change.

**Comment by vedant-jain03** [comment]
Can you do this footer for other pages as well?

**Comment by ashutoshkosti1919** [comment]
I have did it for about us page , donate blood page and donor center location page. And in other pages ,the link is already modified.

**Comment by vedant-jain03** [comment]
@ashutoshkosti1919 Kindly resolve the conflicts.

**Comment by ashutoshkosti1919** [comment]
conflicts resolved

**Pull request merged**
